spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
        uri: mongodb://localhost:27017/qa_sop_po_tool
        database: qa_sop_po_tool
        auto-index-creation: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 4e44b3d100347c
    password: 00d3aa9bc4a209
    properties:
      mail:
        protocol: smtp
        tls: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: sandbox.smtp.mailtrap.io
        debug: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB

server:
  port: 8312
  servlet:
    context-path: /soppotool
    
path:
  fileBasePath: /var/www/html/qa/sop_po_tool/sop_po_tool_be/uploads
  getPath: assets/uploads/

datacapture:
  app:
    jwtSecret: "======================datacapture==========================="
    jwtExpirationMs: 86400000
    jwtCookieName: datacapture

springdoc:
  swagger-ui:
    path: /ui
storage:
  location: documents
  attachments: attachments
  poCopy: poCopy
  chunk: chunk

resttemplate:
  connection:
    timeout: 10000
  read:
    timeout: 60000

com:
  custom:
    reset-link: http://localhost:3000/#/resetpassword
    isSignUp: true

ebrief:
  api:
    url: https://ebriefdev.ckdigital.in/api/po_tool/briefs
    username: brief_submission_user
    password: 5iXOE4gfJ5ITSgT
