# # MongoDB properties

# # spring.data.mongodb.uri=${MONGODB_URI}
# # server.port=8035

# spring.data.mongodb.uri=mongodb://localhost:27017/dev_sop_po_tool
# server.port=8404

# #profilepicture
# # fileBasePath= src/main/resources/static/assets/uploads/attachments
# fileBasePath= /var/www/html/dev/sop_po_tool/sop_po_tool_be/uploads
# getPath =assets/uploads/

# #fileBasePath= uploads/
# #getPath =uploads/

# datacapture.app.jwtSecret= ======================datacapture===========================
# datacapture.app.jwtExpirationMs=86400000
# datacapture.app.jwtCookieName= datacapture


# #Api Doc
# #springdoc.api-docs.path=/api-docs
# #springdoc.api-docs.enabled=true
# #logging.level.root=DEBUG
# #logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
# #logging.level.sop_po.serviceImpl.SapServiceImpl=DEBUG

# springdoc.swagger-ui.path=/ui
# server.servlet.context-path= /soppotool

# #Testing
# #fileBasePath= /var/www/html/uat/sop_po_tool_backend/uploads/
# #getPath =sop_po_tool_backend/uploads/

# spring.mail.host=sandbox.smtp.mailtrap.io
# spring.mail.port=2525
# spring.mail.username=4e44b3d100347c
# spring.mail.password=00d3aa9bc4a209

# spring.mail.properties.mail.protocol=smtp
# spring.mail.properties.mail.tls=true

# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.ssl.trust=sandbox.smtp.mailtrap.io
# spring.mail.properties.mail.debug=true

# resttemplate.connection.timeout=10000
# resttemplate.read.timeout=60000

# spring.servlet.multipart.enabled=true
# spring.servlet.multipart.max-file-size=40MB
# spring.servlet.multipart.max-request-size=40MB

# # logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
