pipeline {
    agent any

    environment {
        NODE_ENV = "production"
        NODEJS_HOME = tool name: 'node-20', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        PATH = "${NODEJS_HOME};${PATH}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/balaguru-k/sop-po-tool.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('sop-po-tool') {
                    bat 'npm install'
                }
            }
        }
        stage('SonarQube Analysis') {
            environment {
                SCANNER_HOME = tool 'SonarScanner'
                
            }
            steps {
                dir('sop-po-tool') {
                    withSonarQubeEnv('SonarQube') {
                        bat "${SCANNER_HOME}\\bin\\sonar-scanner.bat"
                        
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('sop-po-tool') {
                    bat 'docker build -t sop-po-tool:latest .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                dir('sop-po-tool') {
                    bat '''
                    docker stop sop-po-tool-container >nul 2>&1
                    docker rm sop-po-tool-container >nul 2>&1
                    docker run -d --name sop-po-tool-container -p 3000:80 sop-po-tool:latest
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "Application is running at http://localhost:3000"
        }

        failure {
            echo "Build Failed"
        }
    }
}
